- name: System - Install Apache
  apt: pkg={{item}} state=present
  with_items:
    - apache2
    - php5
    - php5-mysql
    - php5-memcache

- include: vhost host=github-tests.local aliases=['www.github-tests.local']
